### ISSUE TITLE
mails with format ASCII only LF line endings are not parsed

### ISSUE THREAD

**Issue by BramEsposito** [jhermsmeier/node-envelope#16]
It looks like only mails with CRLF line endings are parsed. I will look into contributing a patch to fix that.

**Comment by jhermsmeier** [comment]
@BramEsposito that's because the RFC specifies that line endings must be CRLF; see https://tools.ietf.org/html/rfc2822#section-3.5 – emails with LF only line endings are invalid.

**Comment by BramEsposito** [comment]
Hi @jhermsmeier I was double checking my test files and it looks like some might have been mangled somewhere.

So this issue is solved for me: all test files should have CRLF line endings indeed.

**Comment by BramEsposito** [comment]
This came up again: Apple Mail saves eml messages with LF linefeeds instead of CRLF

**Comment by jhermsmeier** [comment]
Okay, interesting – I'll check it out

**Comment by jhermsmeier** [comment]
@BramEsposito I tried to reproduce this, but Apple Mail still saves `.eml`s with CRLF for me;

```
0000  44 65 6c 69 76 65 72 65 64 2d 54 6f 3a 20 6a 68  | Delivered-To: jh |
0010  65 72 6d 73 6d 65 69 65 72 40 67 6d 61 69 6c 2e  | ermsmeier@gmail. |
0020  63 6f 6d 0d 0a 52 65 63 65 69 76 65 64 3a 20 62  | com..Received: b |
```

And even if it is saving them with LF delimited lines, I'd argue that it'd be a bug in Apple Mail
