### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by maxpaj** [jhermsmeier/node-envelope#19]
Would be really nice to have a typescript definition for this.

Is there some documentation from where I can copy all of the definitions?

BTW: Amazing library you've created, I've had a lot of use for it :)

**Comment by jhermsmeier** [comment]
Thanks for the kind words, very appreciated! :)

While I understand the need & usefulness of type definitions, I'm afraid I'd rather not add them, as I'm not a TypeScript user myself, and would most likely fail at maintaining them properly.

Unfortunately, documentation is lacking as well – your best bet will be combing through the code (which isn't a lot (~200 LOC), but a bit convoluted). I've been planning to give this some more work, but time is a limiting factor.

That said, I'd still be happy to accept a PR adding them, if you'd like to give it a go. Alternatively typings could be added over at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), I guess.
