### ISSUE TITLE
node-imap

### ISSUE THREAD

**Issue by AurisAudentis** [jhermsmeier/node-envelope#21]
Does this project support direct parsing of node-imap objects? If it does, I will try and figure out how the code works, and add some documentation and examples for future users.

**Comment by jhermsmeier** [comment]
Hey, this module parses raw emails, no particular object structures, so you'd have to get the entire message (header + body) out of node-imap for them to parse with this (which, looking at the project's README is certainly possible). Not sure if this answers your question, could you give an example of what you're envisioning?

**Comment by AurisAudentis** [comment]
I am looking for a module that helps with the decoding of email messages, but perhaps this is not what I was looking for: is this module meant to only parse files on disk? I'll have a comb through the sourcecode to see if i can find anything useful.

**Comment by jhermsmeier** [comment]
You can give this module any string or buffer, the message doesn't have to be on disk, so i.e. if you want to parse an email from node-imap, you could do something like this:

```js
var fetch = imap.seq.fetch(box.messages.total + ':*', { bodies: [''] });

fetch.on('message', function(msg, seqno) {
  
  var contents = null
  
  msg.on('body', function(stream, info) {
    
    var buffers = []
    
    stream.on( 'readable', function() {
      while( chunk = this.read() ) {
        buffers.push( chunk )
      }
    })
    
    stream.once( 'end', function() {
      contents = Buffer.concat( buffers )
    })
    
  })
  
  msg.once( 'end', function() {
    var email = Envelope.parse( contents )
  })
})
```
